config/routes.rb
Rails.application.routes.draw do
  #top-page
  root 'home#top'
  
  #宿のキーワード検索ページ
  get "hotels/index_keyword_search" => "hotels#index_keyword_search"
  #宿の都道府県検索ページ
  get "hotels/index_prefectures_name_search" => "hotels#index_prefectures_name_search"
  
  get "reservations/:id/index" => "reservations#index"
  
  devise_for :users
  
  resources :hotels do
   resources :reservations
  end
  
  resources :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  validates_presence_of :name, :price, :memo, :address_city, :address_street, :image, :tel
  validates_length_of :name, :address_city, :address_street, :tel, maximum: 50
  validates_length_of :memo, maximum: 500
  
  #宿画像アップロード先の変更
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  has_many :reservations
  
  #検索用
  def self.search(search)
    return Hotel.all unless search
    Hotel.where(['name LIKE ?', "%#{search}%"]).or(where(['prefectures_name LIKE ?', "%#{search}%"])).or(Hotel.where(['address_city LIKE ?', "%#{search}%"]))
  end
  #userが予約したhotelの取得
  def reserved_by?(user)
    reservations.where(user_id: user.id).exists?
  end
  
end

app/controllers/hotels_controller.rb
  class HotelsController < ApplicationController
    before_action :authenticate_user!, except: [:index]
    before_action :ensure_user, only: [:edit, :update, :destroy]
    
    def index
      @hotels = Hotel.all
    end
    #キーワード検索
    def index_keyword_search
      @hotels = Hotel.search(params[:search])
      @search_word = params[:search]
    end
    #都道府県検索
    def index_prefectures_name_search
      hotels_index_prefectures_name_search
      @hotels = @prefecture_keyword
      @search_word = params[:prefecture_keyword]
    end
    
    
    def new
      @hotel = Hotel.new
    end
    
    def create
      @hotel = Hotel.new(hotel_params)
      @hotel.user_id = current_user.id #作成したhotelと作成者のidを紐付け
      if @hotel.save
        redirect_to hotels_path(current_user)
      else
        flash.now[:notice] = "必須項目が記入されていないか、条件をクリアしていません"
        render new_hotel_path
      end
    end
    
    def show
      @hotel = Hotel.find(params[:id])
    end
    
    def edit
    end
    
    def update
      if @hotel.update(hotel_params)
        flash[:notice] = "宿の情報を変更しました"
        redirect_to hotels_path
      else
        flash[:notice] = "もう一度確認の上記入してください"
        render :edit
      end
    end
    
    def destroy
      @hotel.destroy
      flash.now[:notice] = "宿の登録を削除しました"
      redirect_to hotels_path
    end
    
    
    private
    
    def ensure_user
      @hotel = Hotel.find_by(params[:id])
      unless @hotel.user_id == current_user.id
        redirect_to new_hotel_path
      end
    end
    
    def hotel_params
      params.require(:hotel).permit(:name, :tel, :price, :memo, :user_id, :postcode, :prefectures_name, :prefecture_code, :address_city, :address_street, :address_building, :image)
    end
    
    #===============都道府県検索用　名称変換欄=====================
    def hotels_index_prefectures_name_search
      if params[:prefecture_keyword] == '北海道地方'
        @prefecture_keyword = Hotel.where(prefectures_name: "北海道")
      elsif params[:prefecture_keyword] == '東北地方'
        @prefecture_keyword = Hotel.where(prefectures_name: ["青森県", "岩手県", "宮城県", "秋田県", "山形県" ,"福島県"])
      elsif params[:prefecture_keyword] == '関東地方'
        @prefecture_keyword = Hotel.where(prefectures_name: ["東京都", "茨城県", "栃木県", "群馬県", "埼玉県" ,"千葉県" ,"神奈川県"])
      elsif params[:prefecture_keyword] == '北陸・甲信越地方'
        @prefecture_keyword = Hotel.where(prefectures_name: ["新潟県", "富山県", "石川県", "福井県", "山梨県" ,"長野県"])
      elsif params[:prefecture_keyword] == '東海地方'
        @prefecture_keyword = Hotel.where(prefectures_name: ["愛知県", "岐阜県", "三重県", "静岡県"])
      elsif params[:prefecture_keyword] == '近畿地方'
        @prefecture_keyword = Hotel.where(prefectures_name: ["滋賀県", "京都府", "奈良県", "和歌山県", "大阪府" ,"兵庫県"])
      elsif params[:prefecture_keyword] == '中国地方'
        @prefecture_keyword = Hotel.where(prefectures_name: ["鳥取県", "島根県", "岡山県", "広島県", "山口県"])
      elsif params[:prefecture_keyword] == '四国地方'
        @prefecture_keyword = Hotel.where(prefectures_name: ["徳島県", "香川県", "愛媛県", "高知県"])
      elsif params[:prefecture_keyword] == '九州地方'
        @prefecture_keyword = Hotel.where(prefectures_name: ["福岡県", "佐賀県", "長崎県", "熊本県", "大分県" ,"宮崎県" ,"鹿児島県"])
      elsif params[:prefecture_keyword] == '沖縄'
        @prefecture_keyword = Hotel.where(prefectures_name: ["沖縄県"])        
      end
    end
    #===================================================================
  end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/edit.html.erb
<div class="card col-sm-6 mx-auto mt-5">
  <div class="card-body">
    <h3 class="mt-1 mb-3 header-center">宿の編集</h3>
      
    <%= form_with model: @hotel do |f| %>
      <div class="form-floating mb-3">
        <%= f.text_field :name, autofocus: true, autocomplete: "name", :class => "form-control", :id => "floatingInput", :placeholder => "宿の名前" %>
        <%= f.label :name, "宿の名前", :class => "form-label" %>
      </div>
      
      <div class="form-floating mb-3">
        <%= f.text_field :tel, autocomplete: "tel", :class => "form-control", :id => "floatingInput", :placeholder => "電話番号"  %>
        <%= f.label :tel, "電話番号", :class => "form-label" %>
      </div>    
      
      <div class="form-floating mb-3">
        <%= f.text_field :postcode, autocomplete: "postcode", :class => "form-control", :id => "floatingInput", :placeholder => "郵便番号"  %>
        <%= f.label :postcode, "郵便番号", :class => "form-label" %>
      </div>
      
      <div class="form-floating mb-3">
        <%= f.collection_select :prefectures_name, JpPrefecture::Prefecture.all, :name, :name, { prompt: '選択してください' }, :class => "form-control", :id => "floatingInput", :placeholder => "都道府県" %>
        <%= f.label :prefectures_name, "都道府県", :class => "form-label" %>
      </div>
      
      <div class="form-floating mb-3">
        <%= f.text_field :address_city, autocomplete: "address_city", :class => "form-control", :id => "floatingInput", :placeholder => "市区町村"  %>
        <%= f.label :address_city, "市区町村", :class => "form-label" %>
      </div>
      
      <div class="form-floating mb-3">
        <%= f.text_field :address_street, autocomplete: "address_street", :class => "form-control", :id => "floatingInput", :placeholder => "番地"  %>
        <%= f.label :address_street, "番地", :class => "form-label" %>
      </div>
      
      <div class="form-floating mb-3">
        <%= f.text_field :address_building, autocomplete: "address_building", :class => "form-control", :id => "floatingInput", :placeholder => "建物名"  %>
        <%= f.label :address_building, "建物名(マンション名など）", :class => "form-label" %>
      </div>
  
      <div class="mb-3">
        <%= f.label :image, "宿の画像を選んでください（変更しない場合は空欄のままにしてください）", :class => "form-label" %>
        <%= f.file_field :image, autocomplete: "image", :class => "form-control", :type => "file", :id => "formFile" %>
      </div>
      
      <div class="form-floating mb-3 bottom-space">
        <%= f.text_area :memo, autocomplete: "memo", :class => "form-control", :id => "floatingTextarea2", :placeholder => "宿の紹介文", style: "height: 200px" %>
        <%= f.label :memo, "宿の紹介文を記入してください(300字以内)", :class => "form-label" %>
      </div>
      
      <div class="form-floating mb-3">
        <%= f.text_field :price, autofocus: true, autocomplete: "price", :class => "form-control", :id => "floatingInput", :placeholder => "一泊の料金" %>
        <%= f.label :price, "一泊の料金", :class => "form-label" %>
      </div>
      
      <div class="btn-login">
        <%= link_to '削除する', "/hotels/#{params[:id]}", :class => "btn btn-danger", method: :delete %>
        <div class="actions">
          <%= f.submit "宿情報を編集する", :class => "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/hotels/index.html.erb
<% if user_signed_in? %>
<h3 class="mt-1 mb-3 header-center pd-top40">宿　一覧</h3>
<% else %>
<h3 class="mt-1 mb-3 header-center pd-top40">予約や詳細の確認はログイン後にできます</h3>
<% end %>
<div class="input-box">
  <input type="text" class="input-text" placeholder="キーワードを入力">
</div>

<div class="hotels-cord">
  <% @hotels.each do |hotel| %>
  
  <!-- 宿情報表示部 -->
  <div class="card hotels-cord-img" style="margin: 20px; width: 18rem;">
    <image src="<%= hotel.image %>" class="card-img-top" >
    <div class="card-body">
      <h5 class="card-title"><%= hotel.name %></h5>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><%= hotel.prefectures_name %><%= hotel.address_city %></li>
        <li class="list-group-item">一泊一人　¥ <%= hotel.price %></li>
      </ul>
      <% if user_signed_in? %>
      <%= link_to "詳細を見る", hotel_path(hotel.id), {class: "btn btn-primary"} %>
      <% end %>
    </div>
    <!-- real_time_filter  -->
    <div class="keyword-list">
      <p><%= hotel.name %></p>
      <p><%= hotel.postcode%></p>
      <p><%= hotel.prefectures_name%></p>
      <p><%= hotel.address_city%></p>
    </div>
  </div>
  <% end %>
</div>

app/views/hotels/index_keyword_search.html.erb
<h3 class="mt-1 mb-3 header-center">宿　検索</h3>

<div class="search-word">
<h2>検索ワード　[<%= @search_word %>]</h2>
<p>※検索ワードがない場合はすべての宿が表示されます</p>
</div>

<div class="hotels-cord">
  <% @hotels.each do |hotel| %>
  <div class="card" style="margin: 20px; width: 18rem;">
    <image src="<%= hotel.image %>" class="card-img-top" >
    <div class="card-body">
      <h5 class="card-title"><%= hotel.name %></h5>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><%= hotel.prefectures_name %><%= hotel.address_city %></li>
        <li class="list-group-item">一泊一人　¥ <%= hotel.price %></li>
      </ul>
      <%= link_to "詳細を見る", hotel_path(hotel.id), {class: "btn btn-primary"} %>
    </div>
  </div>
  <% end %>
</div>

  <div class="actions btn-back">
    <%= link_to "戻る", :back, :class => "btn btn-primary" %>
  </div>

app/views/hotels/index_prefectures_name_search.html.erb
<h3 class="mt-1 mb-3 header-center">宿　検索</h3>

<div class="search-word">
<h2>検索エリア　[<%= @search_word %>]</h2>
</div>

<div class="hotels-cord">
    <% @hotels.each do |hotel| %>
      <div class="card" style="margin: 20px; width: 18rem;">
        <image src="<%= hotel.image %>" class="card-img-top" >
        <div class="card-body">
          <h5 class="card-title"><%= hotel.name %></h5>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= hotel.prefectures_name %><%= hotel.address_city %></li>
            <li class="list-group-item">一泊一人　¥ <%= hotel.price %></li>
          </ul>
          <%= link_to "詳細を見る", hotel_path(hotel.id), {class: "btn btn-primary"} %>
        </div>
      </div>
    <% end %>
</div>

  <div class="actions btn-back">
    <%= link_to "戻る", :back, :class => "btn btn-primary" %>
  </div>

app/views/hotels/new.html.erb
<div class="card col-sm-6 mx-auto mt-5">
  <div class="card-body">
    <h3 class="mt-1 mb-3 header-center">宿の新規登録</h3>
      
    <%= form_with model: @hotel do |f| %>
      <div class="form-floating mb-3">
        <%= f.text_field :name, autofocus: true, autocomplete: "name", :class => "form-control", :id => "floatingInput", :placeholder => "宿の名前" %>
        <%= f.label :name, "宿の名前", :class => "form-label" %>
      </div>
      
      <div class="form-floating mb-3">
        <%= f.text_field :tel, autocomplete: "tel", :class => "form-control", :id => "floatingInput", :placeholder => "電話番号"  %>
        <%= f.label :tel, "電話番号", :class => "form-label" %>
      </div>    
      
      <div class="form-floating mb-3">
        <%= f.text_field :postcode, autocomplete: "postcode", :class => "form-control", :id => "floatingInput", :placeholder => "郵便番号"  %>
        <%= f.label :postcode, "郵便番号", :class => "form-label" %>
      </div>
      
      <div class="form-floating mb-3">
        <%= f.collection_select :prefectures_name, JpPrefecture::Prefecture.all, :name, :name, { prompt: '選択してください' }, :class => "form-control", :id => "floatingInput", :placeholder => "都道府県"  %>
        <%= f.label :prefectures_name, "都道府県", :class => "form-label" %>
      </div>
      
      <div class="form-floating mb-3">
        <%= f.text_field :address_city, autocomplete: "address_city", :class => "form-control", :id => "floatingInput", :placeholder => "市区町村"  %>
        <%= f.label :address_city, "市区町村", :class => "form-label" %>
      </div>
      
      <div class="form-floating mb-3">
        <%= f.text_field :address_street, autocomplete: "address_street", :class => "form-control", :id => "floatingInput", :placeholder => "番地"  %>
        <%= f.label :address_street, "番地", :class => "form-label" %>
      </div>
      
      <div class="form-floating mb-3">
        <%= f.text_field :address_building, autocomplete: "address_building", :class => "form-control", :id => "floatingInput", :placeholder => "建物名"  %>
        <%= f.label :address_building, "建物名(マンション名など）", :class => "form-label" %>
      </div>
  
      <div class="mb-3">
        <%= f.label :image, "宿の画像を選んでください", :class => "form-label" %>
        <%= f.file_field :image, autocomplete: "image", :class => "form-control", :type => "file", :id => "formFile" %>
      </div>
      
      <div class="form-floating mb-3 bottom-space">
        <%= f.text_area :memo, autocomplete: "memo", :class => "form-control", :id => "floatingTextarea2", :placeholder => "宿の紹介文", style: "height: 200px" %>
        <%= f.label :memo, "宿の紹介文を記入してください(300字以内)", :class => "form-label" %>
      </div>
      
      <div class="form-floating mb-3">
        <%= f.text_field :price, autofocus: true, autocomplete: "price", :class => "form-control", :id => "floatingInput", :placeholder => "一泊の料金" %>
        <%= f.label :price, "一泊の料金", :class => "form-label" %>
      </div>
      
      <div class="btn-login">
        <div class="actions">
          <%= f.submit "宿の登録へ", :class => "btn btn-primary" %>
        </div>
      </div>
      
    <% end %>
  </div>
</div>

app/views/hotels/show.html.erb
  <div class="card col-sm-6 mx-auto mt-5">
    <div class="card-body">
      <h3 class="mt-1 mb-3 header-center">宿　詳細</h3>
      
      <div class="edit-icon">
        <% if @hotel.image.blank? %>
         <p>現在登録中の画像はありません</p>
        <% else %>
         <image src="<%= @hotel.image %>" class="edit-icon-image">
        <% end %>
      </div>
      
      <ul class="list-group">
        <li class="list-group-item">一泊一人の料金　　　:　<%= @hotel.price %></li>
        <li class="list-group-item">宿の名前　　　　　　:　<%= @hotel.name %></li>
        <li class="list-group-item">電話番号　　　　　　:　<%= @hotel.tel %></li>
        <li class="list-group-item">郵便番号　　　　　　:　<%= @hotel.postcode %></li>
        <li class="list-group-item">都道府県　　　　　　:　<%= @hotel.prefectures_name %></li>
        <li class="list-group-item">市区町村　　　　　　:　<%= @hotel.address_city %></li>
        <li class="list-group-item">番地　　　　　　　　:　<%= @hotel.address_street %></li>
        <li class="list-group-item">建物名　　　　　　　:　<%= @hotel.address_building %></li>
        <li class="list-group-item">宿の紹介文　　　　　:　<%= @hotel.memo %></li>
      </ul>
      
      <div class="btn-login">
        <div class="actions">
          <% if @hotel.user_id == current_user.id %>
            <%= link_to "宿の情報を編集する場合はこちら", edit_hotel_path , :class => "btn btn-primary" %>
          <% end %>
          <%= link_to "この宿を予約する", new_hotel_reservation_path(@hotel.id), :class => "btn btn-primary" %>
        </div>
      </div>
      
    </div>
  </div>